# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\STUFF\PORTFOLIO\SOFTWARE CITAS\ui\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setStyleSheet("QWidget#background {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #f74780, stop:1 #fa8fb1);\n"
"}\n"
"QWidget#main_container {\n"
"    background-color: #ffe4ec;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QWidget#float_window {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #f74780, stop:1 #fa8fb1);\n"
"    border-radius: 20px;\n"
"}")
        self.background = QtWidgets.QWidget(MainWindow)
        self.background.setObjectName("background")
        self.main_container = QtWidgets.QWidget(self.background)
        self.main_container.setGeometry(QtCore.QRect(20, 10, 1251, 701))
        self.main_container.setObjectName("main_container")
        self.container = QtWidgets.QWidget(self.main_container)
        self.container.setGeometry(QtCore.QRect(0, 0, 1251, 701))
        self.container.setObjectName("container")
        self.btn_edit = QtWidgets.QPushButton(self.container)
        self.btn_edit.setGeometry(QtCore.QRect(80, 50, 93, 28))
        self.btn_edit.setObjectName("btn_edit")
        self.float_window = QtWidgets.QWidget(self.container)
        self.float_window.setEnabled(True)
        self.float_window.setGeometry(QtCore.QRect(560, -80, 481, 521))
        self.float_window.setObjectName("float_window")
        self.tbl_appointment = QtWidgets.QTableWidget(self.container)
        self.tbl_appointment.setGeometry(QtCore.QRect(20, 140, 1211, 541))
        self.tbl_appointment.setObjectName("tbl_appointment")
        self.tbl_appointment.setColumnCount(10)
        self.tbl_appointment.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_appointment.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_appointment.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_appointment.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_appointment.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_appointment.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_appointment.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_appointment.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_appointment.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_appointment.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_appointment.setHorizontalHeaderItem(9, item)
        MainWindow.setCentralWidget(self.background)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_edit.setText(_translate("MainWindow", "EDIT"))
        item = self.tbl_appointment.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tbl_appointment.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Concepto"))
        item = self.tbl_appointment.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Fecha"))
        item = self.tbl_appointment.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Hora"))
        item = self.tbl_appointment.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Ap. Paterno"))
        item = self.tbl_appointment.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Ap. Materno"))
        item = self.tbl_appointment.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Nombres"))
        item = self.tbl_appointment.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Código"))
        item = self.tbl_appointment.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Estado"))
